#!/usr/bin/env python

import os
import sys

output_file_name = None
start_arg_idx = 1
for argi in range(len(sys.argv)):
    if sys.argv[argi] == "-o":
        output_file_name = sys.argv[argi + 1]
        start_arg_idx = argi + 2

if output_file_name:
    os.environ['PROC_IO_OUTPUT'] = output_file_name

cwd = os.path.dirname(os.path.abspath(__file__))
os.environ['LD_PRELOAD'] = os.path.join(cwd, 'libproc_io.so')

print ("start! %s", sys.argv[start_arg_idx:])
os.execvpe(sys.argv[start_arg_idx], sys.argv[start_arg_idx:], os.environ)
